---
apiVersion: v1
kind: Service
metadata:
  name: delixir-nodes
  namespace: default
spec:
  clusterIP: None
  selector:
    app: delixir
---
apiVersion: v1
kind: Service
metadata:
  name: delixir
  namespace: default
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: delixir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delixir
spec:
  replicas: 4
  selector:
    matchLabels:
      app: delixir
  template:
    metadata:
      labels:
        app: delixir
    spec:
      containers:
      - name: delixir
        image: mrmicahcooper/delixir:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
